### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by TheWeirdDev** [j4cobgarby/atomic-kernel#3] opened 2018-01-28 06:03 UTC
I get this error message from the `make` command.

![screenshot from 2018-01-28 09-27-41](https://user-images.githubusercontent.com/6321734/35479476-ddfceb34-040d-11e8-9684-e211bb4cff05.png)

* OS: `ArchLinux`
* Version: `4.14.15-1-ARCH`

**Comment by j4cobgarby** [comment] 2018-01-29 16:51
I get this error too, when building on my laptop but not when building on my main computer.
I'm not sure why it happens, but I'm trying to fix it.

**Comment by j4cobgarby** [comment] 2018-01-30 16:54
Whoops - didn't mean to close it yet

**Comment by j4cobgarby** [comment] 2018-01-31 16:27
@alireza6677 I was right about the problem. To get it to build properly you need to use a different cross-compiler, I'd suggest [this](https://github.com/rm-hull/barebones-toolchain) toolchain. I've updated the README to reflect this. Thanks for the issue - I had the same problem on my laptop, but it's good to know it wasn't a problem with that alone.

**Closed as completed by j4cobgarby** 2018-01-31 16:27 UTC
Labels: bug, help wanted

**Comment by alireza6677** [comment] 2018-02-01 04:05
@j4cobgarby I can confirm that this compiler works well. Thanks for helping out.

**Comment by alireza6677** [comment] 2018-02-01 11:05
@j4cobgarby Actually in ArcLinux you can compile it with the default `gcc` package, using `-m32` flag.

**Comment by j4cobgarby** [comment] 2018-02-01 13:51
@alireza6677 no problem :)
And is that right? I had no idea that would work, I wonder if that works on other platforms too. I'll add that to the README in my next push

**Comment by alireza6677** [comment] 2018-02-01 15:17
I think the ArchLinux packagers merged the two `gcc` and `gcc-multilib` packages into a single package a few months ago, that might be the reason it works. On the other distributions it might not work.
Also i tried to compile the latest changes with the default gcc and it gave me this error:

```
kern.c:(.text+0x86): undefined reference to `__stack_chk_fail_local'
/usr/bin/ld: dist/kern.elf: hidden symbol `__stack_chk_fail_local' isn't defined
/usr/bin/ld: final link failed: Bad value
```

adding `-fno-stack-protector` flag solved the problem but i don't know what was causing it.

The other cross compiler worked well without showing any errors.

**Comment by j4cobgarby** [comment] 2018-02-01 17:13
@alireza6677 ah, okay. It'll probably be best to stick with i686-elf-gcc, then :)
